---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/juhi/Desktop/SpaceSimulation/app'
relocations:
  - { offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003E70, symSize: 0xCC }
  - { offset: 0x41, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003E70, symSize: 0xCC }
...
